# Permalinks
permalink:           none

markdown: kramdown
kramdown:
  input: GFM

# Setup
title:               What I should have said
tagline:             had I thought what I was saying.
description:         Duncan thinks it though
url:                 http://oneeyedmen.com
paginate:            1
disqusid:            oneeyedmencom
# baseurl:             "http://dmcg.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Duncan McGregor
  url:               https://twitter.com/duncanmcg
  email:             duncan@oneeyedmen.com

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/dmcg

pages_list:
  About: '/about'
  Archive: '/archive'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
